### ISSUE TITLE
Bolus progress message dissapears when app is not visible

### ISSUE THREAD

**Issue by dexdan** [0pen-dash/AndroidAPS#102]
Samsung S7. Issued a 3u bolus. The box came up to say it was being delivered. Pressed phone button to go back to phone home screen. Switched back to AAPS but bolus delivery box had disappeared despite pod bolus being ongoing.
(Suspect this may be an AAPS bug rather than dash specific?)

**Comment by vanelsberg** [comment]
AAPS main, known issue.
Happens when an SMB bolus is running during the time of a manual bolus.
Manual bolus opens progress box waiting for SBM to finish. SBM closes box when finishing.

Not safety issue: Bolus is executed and registered.
When using AAPS wear also bolus progress is reported.
