### ISSUE TITLE
Initial failure to communicate with pod on first setup

### ISSUE THREAD

**Issue by dexdan** [0pen-dash/AndroidAPS#103]
First live on-body test - first use of dash code on S20 (had previously used off-body on my old S7).

Had connection problems both when doing pod initialization (after clicks) and when inserting cannula. Worked when pressing retry a couple of times. See screenshot. If it is significant: an orangelink was near to phone / pod.

@Maes / @Theodoor had similar difficulty connecting to the first pod too, but didn't see this message with subsequent pods. I don't know whether this will apply to me or not (not time for second pod yet).

Related issue: the error message needs to be made more user friendly.

Phone: Samsung S20.
Build 52e18b332 (nb this is 23/8/21 dash code merged with aimi algo)

![Screenshot_20210825-090930_AndroidAPS_connectionfail1](https://user-images.githubusercontent.com/8146651/130863821-3b74a6ad-6ed1-4f97-9eec-70189cf72c36.jpg)
[AndroidAPS_LOG_1629884362988_AFTERconnectionFail.log](https://github.com/0pen-dash/AndroidAPS/files/7049877/AndroidAPS_LOG_1629884362988_AFTERconnectionFail.log)
![Screenshot_20210825-091159_AndroidAPS_connectionfail2](https://user-images.githubusercontent.com/8146651/130863825-7ad45fc9-3bc0-4708-b56f-a64a3e454cfc.jpg)
.

**Comment by dexdan** [comment]
Can confirm this error message did not appear when starting second pod. Suggesting that the issue could be as @vanelsberg suggests. OR it could be to do with interaction with other BT hardware. My first pod (with error) was set up when an orangelink was powered and nearby,  the second pod (without error) wasn't.

**Comment by smokkelaar** [comment]
I had it also the second and the third time.
The MAC address you see in the message is the mac address of the new pod.
![image](https://user-images.githubusercontent.com/35005706/131211752-6f28c4bd-b175-4769-9c78-68cdb4b64dad.png)
![image](https://user-images.githubusercontent.com/35005706/131211758-210394cc-befb-498a-aba6-d1dfe4809d52.png)
![image](https://user-images.githubusercontent.com/35005706/131211766-f0169ba3-72d3-4a01-b6ef-b8d9c6f2814a.png)


And 3 days later:
![image](https://user-images.githubusercontent.com/35005706/131211778-3a7133fa-c27b-44db-b30b-a7e0b75e2a32.png)
![image](https://user-images.githubusercontent.com/35005706/131211780-d38eb543-7195-4acf-aa7b-d04931ad32f0.png)
![image](https://user-images.githubusercontent.com/35005706/131211784-cd295fa6-274a-4844-885f-9054167aa87d.png)

Compared to you, I only see it at Initialize Pod. and not at inserting canula.
First time I rebooted the program, after that it started to work.
In a discussion on discord somebody mentioned that retry also works after some time. and indeed this was also working to get it done.

**Comment by vanelsberg** [comment]
Maybe next time you encounter this problem:
I always make sure no other BT devices are connected (including smartwatch, except the G6 sensor) 
Active BT device communication may impact pairing.

**Comment by vanelsberg** [comment]
Can imagine initial pairing mat take more time, hence timeouts that result in retries.
We need log files on this.

**Comment by vanelsberg** [comment]
Have seen this twice. First time was when activating first DASH on particular hardware.
Retry after waiting about 15 seconds solved the problem both times.

@dexdan Logfiles are missing, so hard to find what is going on?

**Comment by dexdan** [comment]
[Uploading AndroidAPS_LOG_1629884362988.log.zip…]()

**Comment by dexdan** [comment]
Sorry that was earlier log, sorry it didn't upload properly first time

**Comment by smokkelaar** [comment]
[AndroidAPS_LOG_1630269931066.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7073221/AndroidAPS_LOG_1630269931066.log.zip)

Search for DEACTIVATE POD to find the places where i have deactivated the pod.

Log started with active pod (on body)
1st testpod with connection problems  (normal telephone useage)
2nd testpod with connection problems. (disabled all nearby COVID apps, The french and the dutch one)
3rd testpod with connection problems. (Diabled bluetooth devices: wearOS smartwhatch and Tesla app)

4th pod on body without connection problems (killed Xdrip with miaomiao (1) connected)

**Comment by dexdan** [comment]
I do use miaomiao but my second pod didn't have the retry issue. xdrip and miaomiao were live for both. Let's keep monitoring...

**Comment by regiorunner** [comment]
Hi all, just joined the dash test club. At initialisation I experienced simular problems that the initialisation ended with an error message. After 2 trials I put the phone on the pod to minimize distance and the next attempt was immediately succesfull. I remember that the range of the eros pod was limited until initialisation was completed. Maybe it is the same here. I also held the phone on top of the pod when inserting the canula, it worked without problems and fast. I also experience waiting times between 40s and 90s when giving a command for insuline injection unless I put my phone on top of the pod. Then it acts immediately. I suspect the send power of the pod bluetooth is very low.

**Comment by vanelsberg** [comment]
> ...At initialisation I experienced simular problems that the initialisation ended with an error message.
Could you please add logfiles? Without it is almost impossible to know what was going on....

**Comment by vanelsberg** [comment]
@avereha Always the first Pod....
Likely AAPS/DASH initially loaded configuration (including pod state) from AAPS/EROS.
Maybe this is some pod state initializing issue?

**Comment by regiorunner** [comment]
Sorry for late reaction. Attached my first lof file with Dash. 
[AndroidAPS._2021-09-08_16-27-42_.0.zip](https://github.com/0pen-dash/AndroidAPS/files/7147844/AndroidAPS._2021-09-08_16-27-42_.0.zip)

Initializing my second Dash, I put the dash sticker down at the table and positioned the top of the phone against the Dash. Initialisation went ok first time, maximum 10 seconds between intializing and starting clicking of the Dash. (Phone: HTC10, Qualcomm Snapdragon 820, bluetooth 4.2, connection quality 20%, still experience no problems).

**Comment by vanelsberg** [comment]
> ...Attached my first lof file with Dash.
Thanks @regiorunner!
Btw: Do you connect on Discord?

**Comment by regiorunner** [comment]
Checked today the manual of the PDM for the Omnipod Dash.

It states:
During activation of the Pod the PDM and Pod must be placed against each other.
After activation the PDM should be within 1.5 meter (though it can work up till 15 meter).

This confirms the Bleutooth signal is very low until activation is completed and explains succes when putting my phone against the Pod during activation.
Attached the picture of the PDM and Pod during activation from Insulet.

![Dash_Initialisation](https://user-images.githubusercontent.com/90383626/133627803-9360c9d9-80d8-4a0c-944d-dffa9ade7cd3.jpg)

**Comment by avereha** [comment]
Will continue reading #103.
https://github.com/0pen-dash/AndroidAPS/issues/122 fixes the error messages.
