### ISSUE TITLE
Zero deltas shown on main screen

### ISSUE THREAD

**Issue by dexdan** [0pen-dash/AndroidAPS#104]
Main screen shows zero delta / 15min delta / 40min delta, despite this not being the case.
Bg Source is Xdrip (Libre bluetooth). On a mmol-based display.
Thought to be working when NS is the source.

It does sometimes work but I have yet to determine a pattern to when this error occurs. In my experience it mostly (incorrectly) shows zero deltas when it should not. (Initially thought it may be a problem with small values or negatives but it fails in other cases too).

Likely to be an AAPS-main issue?

Phone: Samsung S20.
Build 52e18b332 (nb this is 23/8/21 dash code merged with aimi algo)

![Screenshot_20210825-112559_AndroidAPS_delta1](https://user-images.githubusercontent.com/8146651/130865030-fa7d4909-2ce8-4578-9230-99b0defd96a5.jpg)
![Screenshot_20210825-112604_xDrip+_delta2](https://user-images.githubusercontent.com/8146651/130865033-9de44b99-858d-488f-9c78-e58f7fd5a78e.jpg)

**Comment by vanelsberg** [comment]
Not seeing this....
xDrip+ 2021.03.30 / Dexcom G6
Inter-app setting: Broadcast locally = ON, Send Display Glucose, Compatible Broadcast

**Comment by dexdan** [comment]
This is really odd... the issue now seems to have disappeared after a couple of days! Anyone else seen it? Might it be to do something to do with getting initial data into database?!

**Comment by ToreBj** [comment]
@dexdan  Saw this while using the dev version of aimi-V2-test. Disappeared when I went back to "non-dev". The AndroidAPS-Dash doesn't have it.

**Comment by eurenda** [comment]
Unable to replicate with XDrip _huami_integration-2021.08.22_ and XDrip _Hardware Data Source_ set to _NighScout Follower_

**Comment by dexdan** [comment]
Happy to close given it seems to have ceased happening for me and others have been unable to replicate

**Comment by tim2000s** [comment]
I'd like to reopen this. I've seen it on Dev too.

There is, unfortunately, a randomness. On some occasions the deltas all become zero. At other times they are fine. 

Using Dexcom BYODA with G6.

**Comment by dexdan** [comment]
Opening as per @tim2000s request.

**Comment by vanelsberg** [comment]
AndroidAPS 2.8.2.3-dev Build fdee9e886
S7, BG source is NS: Not seeing this.
S9 Note: BG source is xDrip+/ 2021.03.30 + G6: not seeing this.

**Comment by avereha** [comment]
Can you reproduce this issue with the Virtual pump?
If yes, then let's follow the AAPS bug.

I don't think it is Dash related, but if you see this bug only with Dash, let's continue the conversation here.

In any case, please add logs around the times when you notice this issue.

**Comment by mick711** [comment]
I have this issues but it's for me parameters of Android os the problem. Setting background apps

**Comment by dududu13** [comment]
I also have this issue,
I didn't have with AAPS -AIMI -BOOST -TSUNNAMI form mathieu Tellier
I am using  2.8.2.3-dev with dash pump in engineering mode

**Comment by dududu13** [comment]
I have solved this, with setting pause to NSClient

**Comment by avereha** [comment]
Answered in https://github.com/nightscout/AndroidAPS/issues/689
