### ISSUE TITLE
End of POD (80 hours) => screaming pod

### ISSUE THREAD

**Issue by robertrub** [0pen-dash/AndroidAPS#108]
[AndroidAPS_LOG_1630179568530.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7071485/AndroidAPS_LOG_1630179568530.log.zip)

The first screaming pod (but the first to arrive to the 80h limit too). The pod arrived to its end and instead of an alarm, it became a screaming pod.

![IMG-20210828-WA0008](https://user-images.githubusercontent.com/76626474/131230711-653d123e-5ea2-4ac9-a5a8-61b029570dc1.jpg)

**Comment by vanelsberg** [comment]
Confirming. Think that is because of the lifetime set to 80 hours.
No early warning N hours ahead?

**Comment by robertrub** [comment]
Yes, "pod will end soon" beeps 2 hours (?) before the 80h. No messages/notifications in AAPS (but didn't really pay attention).
Seems like a normal dead pod behavior. I'm closing this issue.

**Comment by vanelsberg** [comment]
Solving through https://github.com/0pen-dash/AndroidAPS/pull/112
