### ISSUE TITLE
Screamer 49 AND bt address not removed for starting next pod 

### ISSUE THREAD

**Issue by dexdan** [0pen-dash/AndroidAPS#109]
![Screenshot_20210829-060807_AndroidAPS](https://user-images.githubusercontent.com/8146651/131239313-3969a793-1f23-4874-8d5b-7b2897e2282d.jpg)
[AndroidAPS_LOG_1630212924637.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7071967/AndroidAPS_LOG_1630212924637.log.zip)
![Screenshot_20210829-052332_AndroidAPS](https://user-images.githubusercontent.com/8146651/131239317-2b3c45a5-0c5f-4b9f-9ce6-364fc5de8bfb.jpg)
![Screenshot_20210829-052128_AndroidAPS](https://user-images.githubusercontent.com/8146651/131239318-12615599-2290-4c0f-bd83-00728eeeb775.jpg)
[AndroidAPS_LOG_1630210205813.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7071968/AndroidAPS_LOG_1630210205813.log.zip)
![Screenshot_20210829-050915_AndroidAPS](https://user-images.githubusercontent.com/8146651/131239320-e7ccc67d-ef78-4a35-9564-2deb3bd648c4.jpg)

Two parts to this report. 

First, had a pod screamer - 49 illegal pump state. See screenshot and first log file. I was asleep at the time, lying on my back with phone just 1-2 metre away. Not sure but looking at treatment screen looks like a temp basal triggered the error. 

I tried to deactivate pod but it wouldn't so 'discarded' the pod and poked the bit in the back to stop the noise. 

Second, tried to start a new pod. After filling, was getting 'illegal state exception' error on trying to set bt address [for new pod] but it already being set [to bt address of old screamer pod]. Retry failed. 

Tried various things to fix this - exited app from ... menu, force stop, clear cache. None worked. Eventually loaded in an old preferences file from my first dash pod, and 'deactivated' that (now non existent) pod, selecting discard. I was then able to setup new pod. See second log file. 

Samsung s20.
Build 0e4a6579e.

**Comment by vanelsberg** [comment]
>I tried to deactivate pod but it wouldn't so 'discarded' the pod
Was this "succesfull" (in Pod view showed "no active pod") or did you get an error?

**Comment by dexdan** [comment]
After pressing deactivate, after a time it came up with a message to say retry or discard. I think I may have done one unsuccessful retry followed by selecting discard. 

I can't remember if / when I got a 'no active pod' message but I'm pretty sure I got this message after discarding.

**Comment by avereha** [comment]
The log file starts at `05:51:49.383`. The error was at `05:09`.
We need earlier logs in order to debug this.

**Comment by dexdan** [comment]
Sorry think had attached the two logs in the wrong order. The second one (...813) starts at 03:53 and ends 05:10 - hopefully that should cover the error?

**Comment by avereha** [comment]
Yes, I found it!
I still can't find 05:09 :(

**Comment by dexdan** [comment]
Great, thanks for the fix
