### ISSUE TITLE
AAPS reports "Illegal_pump_state", only de-activation possible

### ISSUE THREAD

**Issue by regiorunner** [0pen-dash/AndroidAPS#114]
This morning around 6.00 hrs my Dash started intermittend beeping and AAPS mentioned "Illegal pump state". I tried to press in Pod Management "Play Test Beep", but no reaction. Then the Dash started continuus beeping. I pressed "De-activate Pod" and the Dash was correct decoupled and the beeping stopped.

It looks like a Dash failure, and it seems AAPS handled it correct. But this problem I encounter with Eros less than once a year.

To be sure I attached the logfile, interesting lines are:
06:00:29.492 Reporting Illegal Pump State
06:04:06.649 Pressing "Play Test Beep"
06:06:19.226 Command "De-activate Pod"
06:06:30.480 De-activating success

[AndroidAPS.log](https://github.com/0pen-dash/AndroidAPS/files/7147902/AndroidAPS.log)

I initiated a new Dash and that is running now ok for 9 hrs.

**Comment by vanelsberg** [comment]
Thanks for reporting @regiorunner!

Btw: Do you connected to testers on Discord?

**Comment by avereha** [comment]
The logs are starting at `07:18:45.318`. Can you please share earlier logs?

**Comment by regiorunner** [comment]
Attached the log files of my first Dash pump which ended in an "Illegal_pump_state" with continuus beep.

[AndroidAPS._2021-09-09_00-00-00_.1.zip](https://github.com/0pen-dash/AndroidAPS/files/7160867/AndroidAPS._2021-09-09_00-00-00_.1.zip)
[AndroidAPS._2021-09-09_00-00-00_.2.zip](https://github.com/0pen-dash/AndroidAPS/files/7160868/AndroidAPS._2021-09-09_00-00-00_.2.zip)
[AndroidAPS._2021-09-09_00-00-00_.3.zip](https://github.com/0pen-dash/AndroidAPS/files/7160869/AndroidAPS._2021-09-09_00-00-00_.3.zip)
[AndroidAPS._2021-09-10_00-00-00_.0.zip](https://github.com/0pen-dash/AndroidAPS/files/7160870/AndroidAPS._2021-09-10_00-00-00_.0.zip)
[AndroidAPS._2021-09-10_00-00-00_.1.zip](https://github.com/0pen-dash/AndroidAPS/files/7160871/AndroidAPS._2021-09-10_00-00-00_.1.zip)
[AndroidAPS._2021-09-10_00-00-00_.2.zip](https://github.com/0pen-dash/AndroidAPS/files/7160872/AndroidAPS._2021-09-10_00-00-00_.2.zip)
[AndroidAPS._2021-09-10_00-00-00_.3.zip](https://github.com/0pen-dash/AndroidAPS/files/7160873/AndroidAPS._2021-09-10_00-00-00_.3.zip)
[AndroidAPS._2021-09-11_06-34-25_.0.zip](https://github.com/0pen-dash/AndroidAPS/files/7160874/AndroidAPS._2021-09-11_06-34-25_.0.zip)
[AndroidAPS.log](https://github.com/0pen-dash/AndroidAPS/files/7160875/AndroidAPS.log)
[AndroidAPS._2021-09-08_16-27-42_.0.zip](https://github.com/0pen-dash/AndroidAPS/files/7160877/AndroidAPS._2021-09-08_16-27-42_.0.zip)
[AndroidAPS._2021-09-08_16-27-42_.1.zip](https://github.com/0pen-dash/AndroidAPS/files/7160878/AndroidAPS._2021-09-08_16-27-42_.1.zip)
[AndroidAPS._2021-09-09_00-00-00_.0.zip](https://github.com/0pen-dash/AndroidAPS/files/7160879/AndroidAPS._2021-09-09_00-00-00_.0.zip)

If you need more info, let me know.

**Comment by regiorunner** [comment]
This morning, my second Dash also ended after 72 hours in an "Illegal_pump_state" with a continuus beep. Only de-activation was possible. Time was 6.55 CEST 14 September. Reported end time of Pod in AAPS was 14:53 CEST 14 September (note that this reported ending time seemed to be including the 8 hours reserve of the pump).

Additional; info: Phone is HTC 10, chipset Snapdragon 820, bluetooth 4.2.
Interesting aspect might be that I have a very bad connection quality, it ranges between 15% to 20% though the loop seems to function ok. Is there maybe a Bluetooth error counter in te Dash that stops the pump?
The first Dash showed "Illgal_pump_state" roughly after 64 hours.

Attached the last five log files of the second Dash. If you need more, let me know.

[AndroidAPS._2021-09-13_00-02-21_.2.zip](https://github.com/0pen-dash/AndroidAPS/files/7160946/AndroidAPS._2021-09-13_00-02-21_.2.zip)
[AndroidAPS._2021-09-13_00-02-21_.3.zip](https://github.com/0pen-dash/AndroidAPS/files/7160947/AndroidAPS._2021-09-13_00-02-21_.3.zip)
[AndroidAPS._2021-09-14_00-00-04_.0.zip](https://github.com/0pen-dash/AndroidAPS/files/7160948/AndroidAPS._2021-09-14_00-00-04_.0.zip)
[AndroidAPS.log](https://github.com/0pen-dash/AndroidAPS/files/7160949/AndroidAPS.log)
[AndroidAPS._2021-09-13_00-02-21_.1.zip](https://github.com/0pen-dash/AndroidAPS/files/7160950/AndroidAPS._2021-09-13_00-02-21_.1.zip)

**Comment by avereha** [comment]
I checked the last logs, I think https://github.com/0pen-dash/AndroidAPS/pull/116 should fix this.
