### ISSUE TITLE
"Connecting during xx s" does not always start at zero

### ISSUE THREAD

**Issue by regiorunner** [0pen-dash/AndroidAPS#115]
When programming a new bolus, sometimes the connection counter starts at a value larger than zero. I have seen it twice till now.

In the attached logfile there is an example.
 
When I started the bolus by pressing "Ok", the connection counter started at 43 seconds.
Looking in the logfile, it seems a Bluetooth handshaking was going on from a basaal update when the connection for the bolus started.
The timestamp to look for is 13:15:37:068, there the counter value is mentioned I saw when starting the bolus.
The connection counter started at 1 at 13:14:54.733.

Not a problem, but maybe good to understand.

[AndroidAPS_13-38.log](https://github.com/0pen-dash/AndroidAPS/files/7147934/AndroidAPS_13-38.log)

**Comment by avereha** [comment]
This is expected. 
There could be another command(refresh status/smb/etc) that started to be executed before the bolus.
Maybe we should document this?
