### ISSUE TITLE
Initial failure to communicate with pod on first setup (follow-up #103)

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#125]
**AndroidAPS 2.8.2.3-dev**
Build: 09675de3f
Flavor: fulldebug

**Hardware:**
Samsung S7 (SM-G930F, Android 8)
Pod type: U100

**This issue is a follow-up for issue #103 that presumably reports the same problem.**

**Problem description:**
Activating a DASH pod fails on canula insertion, user can "Retry" to complete activation succesfully.

This problem was reported by several users, in many cases on firsts DASH setup on a phone that:
- Had possibly previously run AAPS/EROS
- Settings were imported from an older AAPS/EROS settings file.

_Repro:_
1. Uninstalled previous versions of AAPS and restarted the phone.
2. Installed AAPS in debug mode from AS (cable connected)
3. Completed setup wizard while importing an older **AAPS/EROS settings file** (unencrypted JSON)
4. Validated AAPS was working as expected and receiving BG data from Nightscout (download only)
5 Started activating a Pod while monitoring progress on AS Logcat

Activation failed with an error (see logcat output attached)
`[DashInsertCannulaViewModel$doExecuteAction$1$disposable$1.invoke():71]: Error in Pod activation part 2`
`info.nightscout.androidaps.plugins.pump.omnipod.dash.driver.comm.exceptions.NotConnectedException: Missing session`

See line 312, 2021-09-20 22:37:16.549:

[DASH_ACTIVATION_RETRY-bofore-cannulla.logcat.txt](https://github.com/0pen-dash/AndroidAPS/files/7198961/DASH_ACTIVATION_RETRY-bofore-cannulla.logcat.txt)

**Comment by vanelsberg** [comment]
Remark:
Repro was "successful" in such that I did get the expected failure that could be solved with a single retry.
Unfortunately I can not see any clues on what is going wrong (other the that "connection session lost" is reported)

**Comment by avereha** [comment]
I noticed this error on Samsung phones. The connection was lost a few seconds before:
```
2021-09-20 22:37:12.839 17411-18181/info.nightscout.androidaps I/PUMPBTCOMM: [Binder:17411_4]: [Connection.onConnectionLost():192]: Lost connection with status: 34

```

**Comment by vanelsberg** [comment]
Still strange.

I have seen this error at the end of activation only twice. In both instances I was doing a fresh install while importing settings, at least once with settings from EROS? Both on different phones (S7 and S9).
Coincidence?

**Comment by vanelsberg** [comment]
As hitting retry seems to fix the problem, I would suggest assigning this problem "low priority".

**Comment by avereha** [comment]
From the logs, the issue doesn't seem to be related.

**Comment by vanelsberg** [comment]
Ok. Would suggest closing this issue then.
Maybe keep #103 open for a while to see how this develops?
