### ISSUE TITLE
Samsung A10 under Android 11 will not activate DASH

### ISSUE THREAD

**Issue by robertrub** [0pen-dash/AndroidAPS#127]
A10 was working great with DASH while under Android 10. This noon, the phone updated to Android 11, and I can't activate DASH anymore.

I received "dead" DASH to test (some are 1+ year dead and the last one is only a couple of months overdue). At first I thought that they didn't activate because of "old age" but they are beeping like hell for not being activated yet, they are broadcasting in BT also. I don't think that the problem originates from the "old" DASH but it came with Android 11 on Samsung A10. 

Logs : connection around 16:23 (1+ year old dead pod)

[AndroidAPS_LOG_1632320648188.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7212134/AndroidAPS_LOG_1632320648188.log.zip)

Logs around 16:27. Pod is "dead" 6/2021

[AndroidAPS_LOG_1632320903332.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7212141/AndroidAPS_LOG_1632320903332.log.zip)

Built this morning 

![image](https://user-images.githubusercontent.com/76626474/134377747-c2efa83b-ee97-47a1-baaf-d1c8c5613dd0.png)

BT broadcast of the 3 pods

![image](https://user-images.githubusercontent.com/76626474/134377905-78f32ffe-ad84-4ed7-8678-78a440535774.png)

Error message on AAPS

![image](https://user-images.githubusercontent.com/76626474/134377966-d50e3606-3f3f-425f-bf9c-cf41d3a7c17e.png)

**Comment by robertrub** [comment]
More info. The same BT scanner on my S9 (android 10) phone and on the A10 (Android 11) phone. The A10 does NOT see the pod... Very strange. 
![image](https://user-images.githubusercontent.com/76626474/134387852-31ae1886-b4bc-43ca-a680-ad56239132c7.png)
![image](https://user-images.githubusercontent.com/76626474/134387898-6189929f-3816-4d55-925d-72bd78d9bfcf.png)

**Comment by kakoni** [comment]
There is this on-going issue in googles tracker about android 11 BT issues on various phones; 
https://issuetracker.google.com/issues/168233990

Perhaps related?

**Comment by avereha** [comment]
I don't know if there is anything we could do for this phone model more than mark it as not supported?

**Comment by avereha** [comment]
Please reopen if you think we could do something about this model.
