### ISSUE TITLE
2.8.2.3 Dev / DASH : No pod activated but UI shows a basal distribution

### ISSUE THREAD

**Issue by robertrub** [0pen-dash/AndroidAPS#128]
I have built the latest version via the DASH branch. No pod is activated but AAPS is showing a basal blue line on the graph.

Built this morning

![image](https://user-images.githubusercontent.com/76626474/134383816-8ee10c6c-7e39-4317-9f8c-75c1e50244dd.png)

The graph

![image](https://user-images.githubusercontent.com/76626474/134383845-27fd438b-5275-4851-b342-4d1627cfca14.png)

Milos said that it was a DASH driver problem :)

**Comment by avereha** [comment]
Please add logs

**Comment by robertrub** [comment]
AAPS on tablet (Lenova Android 10), all AAPS data wiped. I start AAPS, give permission, restart AAPS, import setting exported from 2.8.2 main. Setup BG imported from NS, no upload to NS, profile selected and activated, pump DASH selected (can't recall which was done first). No pod activated.

Screen capture. You see a basal rate and the graph shows a basal delivery. FWI, this basal rate DID NOT come from NS (my personal AAPS uses SMBs and basals are ON and OFF all the time)

![Screenshot_2021-09-23-13-03-28-575](https://user-images.githubusercontent.com/76626474/134507808-926c005b-86e9-4300-a4e5-e165379b68c1.jpeg)

The log

[AndroidAPS_LOG_1632394718867.log.zip](https://github.com/0pen-dash/AndroidAPS/files/7217547/AndroidAPS_LOG_1632394718867.log.zip)

Hope this helps. Drop a message is you need more.
