### ISSUE TITLE
Missing pump and configuration data in devicestatus

### ISSUE THREAD

**Issue by ToreBj** [0pen-dash/AndroidAPS#141]
Currently there is no data for pump configuration in devicestatus. Nothing can be seen in in NS while hovering over Pump pill.

Attached is devicestatus JSON from Dash:

![image](https://user-images.githubusercontent.com/23278852/136391133-9fb21fb7-7975-4b09-9528-4f981c34415e.png)

As a comparison I'm also attaching the output from the Eros implementation:

Pump:
![image](https://user-images.githubusercontent.com/23278852/136393289-87994010-d041-4dde-bfe1-4151f033f4c8.png)

Configuration:
![image](https://user-images.githubusercontent.com/23278852/136392812-083afc22-b6aa-49dc-a5f2-2882d6a9eb91.png)

![image](https://user-images.githubusercontent.com/23278852/136393863-8f9e535c-6214-496f-8a71-1a758d7de6a2.png)

**Comment by vanelsberg** [comment]
Confirming "Pump" info is not showing for me on NS
![image](https://user-images.githubusercontent.com/45144129/136474089-89db48f7-d44a-4840-9910-b4be6b8c9b3e.png)

**Comment by vanelsberg** [comment]
Not implemented yet...
(OmnipodDashPumpPlugin.kt getJSONStatus())

**Comment by avereha** [comment]
https://github.com/0pen-dash/AndroidAPS/pull/143

**Comment by ToreBj** [comment]
@avereha  The configuration object is still missing?
