### ISSUE TITLE
Display suspend button is not working

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#34]
`sp.getBoolean(R.string.omnipod_common_preferences_suspend_delivery_button_enabled, false)` seems to always return false, even if I check the box in settings.

**Comment by avereha** [comment]
I think all the Dash settings are not saved or read correctly(I tried TBR beeps too)

**Comment by avereha** [comment]
Fixed with https://github.com/0pen-dash/AndroidAPS/pull/40

**Comment by vanelsberg** [comment]
> Fixed with #40

Check!
