### ISSUE TITLE
Display `deliveryStatus`

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#35]
I'm currently displaying it in the 'Pod Status' field. 
It would be nice if it had it's own field. Should we show it only in debugging mode? If yes, maybe we could add other fields useful for debugging: "number of connection issues, number of unconfirmed commands, etc."

**Comment by avereha** [comment]
Talked with @bartsopers and we are going to display this only for "debug mode"

**Comment by avereha** [comment]
Done.

**Comment by vanelsberg** [comment]
> Talked with @bartsopers and we are going to display this only for "debug mode"

Are we talking "debug mode" (build) or "engineering__mode"?

**Comment by avereha** [comment]
Currently, it's displayed in "debug mode"(build). We could update the condition to engineering__mode if you think it would be better.

**Comment by vanelsberg** [comment]
Under circumstances 'Pod Status' could maybe give useful information.
Was just thinking 'engineering__mode' is more accessible for testers or general troubleshooting?
