### ISSUE TITLE
invalidateTemporaryBasal is not working

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#37]
It seems that this function is expecting a temporary basal id, but we don't have this.
Possible solutions:
 - update it to received pumpId, pumptype, serial number
 - get the Id(from history?)

**Comment by avereha** [comment]
Fixed

**Comment by vanelsberg** [comment]
Not sure how to test this?

**Comment by avereha** [comment]
Uncomment
```
  // XXX use this to test "failed to confirm" commands
```
try multiple times until a temp basal is unconfirmed.

First, make sure it appears successful(both in NS and in the Treatments tab).
After pod status refresh, when it is denied with success, it should go away from both places.
