### ISSUE TITLE
Overview display refresh

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#38]
In a few cases(temp basal change, profile switch), data on the main overview display(for example current basal rate) is not refreshed. 
It does get refresh after max 1 min during the periodic refresh

**Comment by vanelsberg** [comment]
Confirming. seeing this too.

**Comment by vanelsberg** [comment]
Confirming, but not seeing refresh rate at 1 minute.
(I'd say overview is refreshing once recalculations are done, which is triggered by new incoming sensor data?)

**Comment by avereha** [comment]
I think we had two issues here:
 * the overview was not updated after pod commands. This was fixed with: https://github.com/0pen-dash/AndroidAPS/commit/2e8a81f38de1e01ff782fea3fb8d07badae16b49
 * https://github.com/0pen-dash/AndroidAPS/issues/65
I'm closing this because half of it should be fixed and for the other half, we have another issue.
Please reopen if this is not correct.
