### ISSUE TITLE
activation: check deliveryStatus

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#48]
If the app closes during the activation process, it can't resume. It will issue the last command again.

**Comment by avereha** [comment]
How to test:
Take each step in `createActivationPart1Observables` and `createActivationPart2Observables` and remove
`doOnComplete`
and add *above* it:
```
observables.add(Observable.error(java.lang.IllegalStateException("Test")))
```

**Comment by vanelsberg** [comment]
Did some testing using Fake pod. Not a test really, but from the debugger is somewhat confirmed resume-flow us OK.
Needs further testing. Postponed testing this further because of high risk loosing Pod during activation...
