### ISSUE TITLE
timeOnPod

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#55]
Due to the way we are currently calculating it, if it gets out of sync we have no way to sync it back.
Maybe sync timeOnPod on each Basal update?

**Comment by vanelsberg** [comment]
Looking into EROS code:
AapsOmnipodErosManager.java,
`public PumpEnactResult setTime(boolean showNotifications) -> createSuspendedFakeTbrIfNotExists()`

I'd say it uses a temprary Basel to sync?

**Comment by avereha** [comment]
For now, I just display the 'time on pod' with a different color
