### ISSUE TITLE
pod activation time

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#58]
What is considered to be the pod activation time?
 * LTK negotiation ?
 * setUniqueId?
 * compute it from the number of "minutesOnPod"?

**Comment by vanelsberg** [comment]
First think that comes to mind: "ask the pod" (e.g. current datetime minus "minutesOnPod")

Thinking about this: Is the (technically) exact activation time registered of any importance?
As a user I would regard pod activation time as when last command in the actual activation sequence was executed successful?

**Comment by avereha** [comment]
Yes, currently we are using 'minutesOnPod' and it seems to work ok.
Will close for now and reopen if we notice any issues with this approach.
