### ISSUE TITLE
units remaining is incorrect

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#61]
The number of units remaining units is reported as: ~37U for a while, and then it "jumps" to 50U and goes down from that.

**Comment by vanelsberg** [comment]
Have not been able to repro this,
But will keep an eye on this....

**Comment by vanelsberg** [comment]
Can not repro...

**Comment by avereha** [comment]
This might help to find it when it happens: https://github.com/0pen-dash/AndroidAPS/issues/71

**Comment by avereha** [comment]
Closing for now, let's reopen if we can reproduce.
