### ISSUE TITLE
AAPS main overview is not aware of "no Pod active" state.

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#62]
Observed on avereha/conn branch, commit eb33e89ea75ed0fc95a9e9936f18210eb917019b
(Possibly not a driver related)

AAPS doesn't seem aware of no Pod active.
After de-activating the Pod just before expiration, main overview is not reset:
* Current basel rate (based on profile) is displayed.
* Insuline/Cannula age counters still counting byond the Pod's livetime
* Bolus/treatment buttons are still active (using correctly results in the "Bolus delivery error" pop-up)

**Comment by avereha** [comment]
Do we still have this issue?

**Comment by avereha** [comment]
Should be fixed with https://github.com/0pen-dash/AndroidAPS/pull/84

**Comment by vanelsberg** [comment]
I think this issue can be closed?
