### ISSUE TITLE
Main overview update delays: entering carbs

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#65]
**AndroidAPS 2.8.2.2-dev**
Build: 2e8a81f38
Flavor: fullrelease

**Phone:**
Samsung Note9 (SM-N960F, Android 10)

**Problem description:**
Main overview update delays:
Manually entering carbs does not update the COB value under the carbs icon in main overview.
It will eventually update when new calculations are started on receiving BG sensor data

_Additional "context" info:_
Think this is an AAPS main issue?

**Comment by avereha** [comment]
Yes, I also think this issue is AAPS specific.

**Comment by avereha** [comment]
I think was fixed in the dev branch. Please reopen if you still notice this.

**Comment by vanelsberg** [comment]
Confirming: solved
