### ISSUE TITLE
Immediately after activation DASH tab reports "Total delivery: 2.90U"

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#67]
**AndroidAPS 2.8.2.2-dev**
Build: 2e8a81f
Flavor: fullrelease

**Phone:**
Samsung Note9 (SM-N960F, Android 10)

**Problem description:**
After activation DASH tab report "Total delivery: 2.90U".
Suggested value: 0.0U (or 0.3U when taking initial priming in account?)

_Additional "context" info:_
Some insulin is used to prime the Pod during activation just before canula injection.
One could argue this is also insulin "used", but this insulin is not actually "delivered" on-body.

_Repro:_
Activate new DASH pod,
on successful activation, check DASH tab for the value shown at "Total delivery:"

**Comment by avereha** [comment]
Let's leave it like this/maybe change the wording?

**Comment by vanelsberg** [comment]
Yes. Ok with that solution!
