### ISSUE TITLE
Test-plan for testing insulin delivery reported vs actually delivered

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#69]
**AndroidAPS 2.8.2.2-dev**
Build: n.a.
Flavor: n.a.

Phone:
n.a.

**Problem description:**
We need some test-plan defining how to verifying insulin delivery, comparing:
- Insulin delivery reported by AAPS
- Actually insulin delivered by the pump
The above should be identical.

_Required testing:_
- Bolus commands.
- Basal rates.
- Default pod basal rates programmed on activation.

_Possible measuring methods:_
- Counting Pod pump ticks.
- Checking total insuline delivered during a specific time window.
- Logfile/History versus "Total delivery:" om DASH overview.
- ....

**Comment by vanelsberg** [comment]
**On counting Pod pump ticks.**
Hint:  I used the phones voice recorder app to record the Pod ticks:
1. Make sure the Pod is at some fixed basal rate you want to test
2. Make sure you are in a quiet environment
3. Place the phone as close as possible to the Pod and start a voice recording session
4. Go watch your favorite YouTube channel ...
5. When done, check the recording for the ticks (interval time, total number over time) and check if they match

_Calculatuons_:
basalrate (U/h) = (Ticks * 0.05U)  /  time_in_hours

**Example**:
10 Pod ticks in 15 minuttes:
basalrate = (10 * 0.05u) / 0.25h = 2 u/h

**Comment by vanelsberg** [comment]
I think most if this is now in the WiKi?
https://github.com/0pen-dash/AndroidAPS/wiki/3.-What-&-how-to-test

**Comment by avereha** [comment]
Closing this as we don't seem to use it. 
Please reopen if you think we need it.
