### ISSUE TITLE
pod ID: use a random number?

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#72]
For now we are using `4241` for the pod ID and `4242` for the phone ID.
Should we pick a random number here?

**Comment by vanelsberg** [comment]
Unless these ID's are reflected in BT I can not see how this would be a problem unless you'd want to run two Pods concurrently - which ins't supported by AAPS in the first place.

Expect the Pod to be bound based on its MAC so fixed ID this should not be a problem with multiple phones/pods in the same room.

Q: Do not think it is a requirement to support this scenario, but could phone ID be a problem when trying to move an active Pod to another phone?

**Comment by avereha** [comment]
Sounds good, all pods will have the ID `4241` :)

I don't think it will be possible to switch phones(we could test that!) after a pod is activated anyway.
This is because the pod might not accept Bluetooth connections from a different phone.

**Comment by vanelsberg** [comment]
>This is because the pod might not accept Bluetooth connections from a different phone.

Of coarse. Did not think of that. Was just thinking in terms of MAC, but there is much more to it then just that.
No problem!
