### ISSUE TITLE
LOT and Sequence number reported on DASH overview do not match what is printed on the Pod.

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#75]
**AndroidAPS 2.8.2.2-dev**
Build: 97b228728
Flavor: fullrelease

**Hardware:**
Samsung Note9 (SM-N960F, Android 10)
Pod type: U100

**Problem description:**
Pod LOT and Sequence number reported on DASH overview do not match what is printed on the Pod.

_Example:_

LOT: PD1C09302011 / 0033843 (printed on the Pod)
LOT: 135563537 / 853322 (reported on overview)

_Repro:_

1. Activate a Pod.
2. Check the LOT and Sequence number on the DASH overview against what is printed on the Pod

**Comment by avereha** [comment]
I just tested with the original PDM and it has the same bug.
It displays the serial number correctly, but the lot number does not.
I'm not sure there is too much we could do about this issue.

**Comment by vanelsberg** [comment]
Ok, Good test!
So this is either a bug - or intentional and the "LOT" is of internal meaning for Insulet?

To prevent getting this reported again nd again by users, maybe rename the "LOT Number" field name to something else (POD number?), then close this issue?

**Comment by Maes152** [comment]
For me the lot number is incorrect but the sequence number matches.

**Comment by dexdan** [comment]
If it helps to determine any pattern/relation:
I have pod printed with PD1C07222051 1200379
Dash tab shows: Unique ID 4241 / LOT 135554641 / Seq 1200379

**Comment by robertrub** [comment]
I confirm. Here are my numbers id needed

![Screenshot_20210829-090521_Discord](https://user-images.githubusercontent.com/76626474/131241812-5e1ead19-bdfa-46d9-a258-c3598f0c1295.jpg)

**Comment by avereha** [comment]
https://github.com/0pen-dash/AndroidAPS/pull/131
