### ISSUE TITLE
Test unconfirmed commands

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#77]
What: 
We can simulate 'unconfirmed commands'. 
An unconfirmed command is a command that was sent to the pod and then we don't know if the pod received(or executed it).
 
How to:
Search for 'XXX use this to test' and remove comments around that block. 
There are two types of simulations we can do here:
 * pretend that an unconfirmed command failed to execute
 * pretend that an unconfirmed command was executed

What to expect?
Various notifications&alerts(see also settings for enabling sound for those notifications) or error messaged.
When there is an unconfirmed command, all the other commands will fail. 
The way to recover is to 'get pod status' - we do this periodically(every minute) and the same can be executed by hand.

**Comment by vanelsberg** [comment]
Tested. No issues found.
