### ISSUE TITLE
Suspend: alert when delivery is suspended

### ISSUE THREAD

**Issue by avereha** [0pen-dash/AndroidAPS#78]
Configure alert to beep every 15 min if delivery is suspended.

**Comment by avereha** [comment]
https://github.com/0pen-dash/AndroidAPS/pull/79

**Comment by vanelsberg** [comment]
Tested:
1st+2nd+3th "beep": OK.
(Alerted through beeps on AAPS)

**Comment by avereha** [comment]
I tried to enable beeps on the pod and gave up on the idea.
This is more complicated than I thought.
The alert has to be configured for each suspend and disabled on each resume/set basal.

**Comment by vanelsberg** [comment]
Think current implementation is just fine!
