### ISSUE TITLE
Alert: "Timezone on the Pod is different from the timezone on phone..." (timezone in podstate wrong?)

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#80]
**AndroidAPS 2.8.2.2-dev**
Build: avereha/suspend-beep #ae8ba84a
Flavor: fullrelease

Hardware:
Samsung Note9 (SM-N960F, Android 10)
Pod type: U100

**Problem description:**
After updating to this build started getting repeated alerts: "_Timezone on the Pod is different from the timezone on phone. Baselrate is incorrectSwitch profile to fix" alert_".

**Switching profile does not fix**

_Additional info:_
DASH Overview showed Time on Pod as "8/3/21 23:15 (GMT+01:00)", colored MAGENTA.
* Time matches that of the Phone and is correct. Checked that it is in GMT+02:00 CEST.
* Time on Pod showing about 1-2 minutes behind on Phone.
Switching profile does not fix....
FYI: Tried suspend/unsuspend again, refresh, restart phone. No change.

Exported preferences JSON and checked podstate: is says "timezone": "GMT+01:00".
That is wrong? Only location where I can find timezone in podstate  is updated is at observeSendProgramBasalCommand?

        }.doOnComplete {
            podStateManager.timeZone = TimeZone.getDefault()
        }

Logfiles:
[AndroidAPS_LOG_1628026986171.log.zip](https://github.com/0pen-dash/AndroidAPS/files/6927495/AndroidAPS_LOG_1628026986171.log.zip)

Preferences JSON
[2021-08-04_004638_full.json.zip](https://github.com/0pen-dash/AndroidAPS/files/6927502/2021-08-04_004638_full.json.zip)

**Comment by vanelsberg** [comment]
Was checking git history on OmnipodDashPodStateManagementImpl.kl, line 120:

Original values was daylight: "true", changed to "false" with latest commit?
https://github.com/0pen-dash/AndroidAPS/commit/a77a0b21fb9290c0c187fea9807d00fc93b7df32(edited)

**Comment by avereha** [comment]
Yes, I reverted that change and added more logging.
Let's close this for now and reopen if we get new timezone issues.

**Comment by Maes152** [comment]
I have this issue every 30 minutes-ish. 
Running Samsung S7. 
Build: 2a076a566-2021.08.10-08:58

Log file included. Only lines of note I can find are:
`12:06:16.637 [main] D/PUMPCOMM: [OmnipodDashPodStateManagerImpl.getSameTimeZone():130]: sameTimeZone currentTimezone=CEST currentOffset=7200000 podOffset=0`
[AndroidAPS.log](https://github.com/0pen-dash/AndroidAPS/files/6960747/AndroidAPS.log)

**Comment by vanelsberg** [comment]
@avereha I this maybe the issue you mentioned about currentTimezone=CEST vs currentTimezone=GMT+2

**Comment by avereha** [comment]
https://github.com/0pen-dash/AndroidAPS/pull/84 contains another attempt to fix it.
If this doesn't work, the next idea is to compare offsets from UTC.

**Comment by avereha** [comment]
let's comment/reopen if this happens again
