### ISSUE TITLE
DASH Preferences: option "DST/Time zone detection" has no effect

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#81]
AndroidAPS 2.8.2.2-dev
Build: avereha/suspend-beep #ae8ba84a
Flavor: fullrelease

Hardware:
Samsung Note9 (SM-N960F, Android 10)
Pod type: U100

Problem description:
AAPS is in a state where I get an "Timezone on the Pod is different from the timezone on phone...." alert.
Disabling this check (and related alerts) through the option "DST/Time zone detection" under DASH Preferences has no effect?

**Comment by avereha** [comment]
I commented out that option for now.
What is supposed to do if it's enabled?

**Comment by avereha** [comment]
Closing this. 
Let's reopen if we should have that option available.

**Comment by vanelsberg** [comment]
>What is supposed to do if it's enabled?

Not sure. Suppress alerting? Will check EROS code if I can find out some more on this.

>Let's reopen if we should have that option available.

Yes!
