### ISSUE TITLE
Connection quality 0/0 = 1%

### ISSUE THREAD

**Issue by robertrub** [0pen-dash/AndroidAPS#83]
Minor, small (probably) rounding bug. 0 good connections over 0 total connections gives a result of 1%
![IMG-20210807-WA0002](https://user-images.githubusercontent.com/76626474/128600854-fdce7894-60d5-481a-b547-f4f2a7e109eb.jpg)

**Comment by avereha** [comment]
Fixed with https://github.com/0pen-dash/AndroidAPS/pull/86
