### ISSUE TITLE
Screamer: AAPS alerted "ALARM_SAWCOP_RESET

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#85]
**AndroidAPS 2.8.2.2-dev**
Build: 2680402f2
Flavor: fulldebug

**Phone:**
Samsung Note9 (SM-N960F, Android 10)

**Problem description:**
At about 2 hours activation the Pod ended with a Pod error 16 (screamer): AAPS alerted "ALARM_SAWCOP_RESET"
Pod lost.

Time of event:
2021-08-10, 02:21:24.160 (See AndroidAPS._2021-08-10_02-35-35_.0.log, ALARM_SAWCOP_RESET

Logfiles:
[AndroidAPS_LOG_1628579067022.log.zip](https://github.com/0pen-dash/AndroidAPS/files/6960996/AndroidAPS_LOG_1628579067022.log.zip)

**Comment by vanelsberg** [comment]
See also
https://github.com/AAPS-Omnipod/AndroidAPS/issues/54

**Comment by avereha** [comment]
From the logs, that pod had a 20% success connection rate(11 out of 50)

**Comment by vanelsberg** [comment]
Had been seeing lower success rates the past week (~80%).
For the Pod I activated last night it is at 95% (~18 hrs later) as usual.

But expect this to be hardware (Pod) related. Haven seen any problems on connections on any of the pods I tested. Non had "unusual" connection problems . Out of a total of 9 pods, this is my first screamer...

**Comment by avereha** [comment]
This looks like a bad pod error, please reopen if you get this more often.
