### ISSUE TITLE
Treatment button is disabled when no Pod active.

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#87]
**AndroidAPS 2.8.2.2-dev**
Build: e318a1a23
Flavor: fulldebug

**Problem description:**
When no Pod is active, buttons on AAPS overview are all disabled, including the "Treatments" button.
As a result user can no longer register treatments like carbs or insulin administered manually while no active Pod.
This would lead to incorrect COB/IOB once a pod is activated.

**Change request:**
Please consider keeping the treatments button enabled, also with no Pod active.

**Comment by avereha** [comment]
I would move this to AAPS, it is not dash related.

From what I noticed, you can enter this after you activate a new pod(you can select time in the past  in the treatments dialog), so I don't think it is a bug.

**Comment by vanelsberg** [comment]
> I would move this to AAPS, it is not dash related.
Agree.

And yes, one can enter later. But imho disabling treatment when the pump is offline this way  is totally unlogical.
If pump is not working treatment go on (carbs, but also maybe insulin by using pen). Once the pump becomes active ithis would be important missing/required information.

Wil bug this as an issue on main.
