### ISSUE TITLE
Reservoir insuline left not correctly updated

### ISSUE THREAD

**Issue by smokkelaar** [0pen-dash/AndroidAPS#90]
I see some strange behaivor around the reservoir.

![image](https://user-images.githubusercontent.com/35005706/129872391-5e9397a1-b109-4c89-8cd0-a5cae53c7f5a.png)

The total maximum reservoir is around 200 units.
but in this case it is arround 226 units according to the information on the screen.
The Pod did give an alarm (beep-beep   beep-beep)at this time that i recognize as a LOW_RESERVOIR alarm.
According to this information i assume that the total deliverd insuline is the right value. and that the Reservoir displays the wrong value at this time.

later on this information has corrected itself:
![image](https://user-images.githubusercontent.com/35005706/129873973-979e0dd4-4237-4970-8a18-3c25e6b8d950.png)

**Comment by vanelsberg** [comment]
On the first screenshot: did you try REFRESH to update "reservoir left"?

**Comment by smokkelaar** [comment]
No i did not, will try to verify this next time if this will solve the issue.
On the other side, the screen motioned a connection 2 minutes ago.

A small test with a little bit less difference did update the reservoir after pressing Refresh.
so its seems it is only a cosmetic problem.

**Comment by smokkelaar** [comment]
Looked again at this issue.
The reservoir has been filled again according to the software.
It is still the same pod as mentioned above.
See the added screenshots:
![image](https://user-images.githubusercontent.com/35005706/129908768-3d022f6b-d7ec-4d73-bb03-b9e8173b5907.png)
![image](https://user-images.githubusercontent.com/35005706/129908815-d8412431-9d39-4517-9b73-7665663a3afc.png)

Those screenshots were taking after multiple refreshes that didn't solve the problem.

**Comment by vanelsberg** [comment]
Seeing the 3th screenshot, you are not running in developer mode?

**Comment by vanelsberg** [comment]
Hard to say as the screenshots are not related in time. But it is clear number don't add up as expected.
Must have something to do with refresh and status synchronization is respect to resevoir, delivered and bolus running.
Thanks for reporting!

**Comment by avereha** [comment]
Can you please share logs around the times that the screenshots were taken?
