### ISSUE TITLE
Silence alerts not alway visible when alert is going off.

### ISSUE THREAD

**Issue by smokkelaar** [0pen-dash/AndroidAPS#91]
The Reservoir Alarm was going of at the pod, but it was not possible to silence or acknowledge this alarm.
Later on this became visible. It would be nice to actively silence the alarms on the pod when they appear.
even when the app did not notice it yet at that moment in time.

No silence button:
![image](https://user-images.githubusercontent.com/35005706/129874622-c68e6a73-4cab-413b-8a6e-c102ed0a4afc.png)

After some minutes it appears.:
![image](https://user-images.githubusercontent.com/35005706/129874716-b0e7fb63-ce27-442a-91fc-9a3c81d2f90e.png)

**Comment by vanelsberg** [comment]
Did you try REFRESH? It should show the alert in overview after.
I think the Pod overview is not actively updated when an event occurs on the Pod.
However overview should update on next commend or REFRESH.

**Comment by smokkelaar** [comment]
Will focus on that question next time i will encounter this!.

**Comment by avereha** [comment]
please reopen if it doesn't work after REFRESH
