### ISSUE TITLE
Pod Expires date is not static.

### ISSUE THREAD

**Issue by smokkelaar** [0pen-dash/AndroidAPS#92]
Not sure this is a issue, more a observation.
The pod Expires date is changing during the day.
did not found a root course of this behavior.
start of the pump:
![image](https://user-images.githubusercontent.com/35005706/129875232-9bde23eb-9840-4875-aa39-da10bc96e41f.png)

2 days later:
![image](https://user-images.githubusercontent.com/35005706/129875285-fa7db5c8-a371-4a3f-9389-39b43025db89.png)

Not direct a problem but i don't know what kind of effect this has in other parts of the program.

**Comment by vanelsberg** [comment]
Possible cause:
Pod expiry is calculated from (current time + pod_lifetime - minutes_since_activation)
Expect REFRESH pod state or executing a command to update expiry date/time?

Possible solution more accurate time display:
In calculations, replace ZonedDateTime.now() to datatime from "lastStatusResponseReceived"?

**Comment by smokkelaar** [comment]
Yes Refresh did update the pod expiring moment to the original one!

**Comment by dexdan** [comment]
I can confirm I see the same thing as reported. In fact, I was looking at the dash tab and the 'pod expires' time increased by one minute without me doing anything.

**Comment by Thomas-Wolff** [comment]
I can also confirm this behaviour.
The only difference is that as soon as AAPS accesses the DASH Pod, the time returns to its original value
![Screenshot_20210829-133624_AndroidAPS 2](https://user-images.githubusercontent.com/59526802/131251199-5d917356-0491-403f-9791-1131470d6fc1.jpg)
![Screenshot_20210829-133624_AndroidAPS 1](https://user-images.githubusercontent.com/59526802/131251215-d462754c-1ce3-4aac-aa3d-f4afa49ea8a5.jpg)
e.

**Comment by vanelsberg** [comment]
Solved, ready for review and testing:
https://github.com/0pen-dash/AndroidAPS/pull/113
