### ISSUE TITLE
Basal rate displayed has not been correctly updated on local profile activation.

### ISSUE THREAD

**Issue by dexdan** [0pen-dash/AndroidAPS#93]
![20210818_185906_BASAL_RATE_DISPLAY](https://user-images.githubusercontent.com/8146651/129967764-ce8b543a-8a2c-4a17-9e1f-8cd4d2d14de0.jpg)
[AndroidAPS_LOG_1629310178332_BASAL_RATE_DISPLAY.log](https://github.com/0pen-dash/AndroidAPS/files/7010027/AndroidAPS_LOG_1629310178332_BASAL_RATE_DISPLAY.log)
![20210818_185933_BASAL_RATE_PROFILE](https://user-images.githubusercontent.com/8146651/129967771-8c7beb8a-ed6a-401c-ba47-30c478728818.jpg)

I changed local profile from 0.8 to 10u/hr & activated, got message to say 'profile set ok'. Pod appears to be delivering 10u/hr but display still indicates 0.8u/hr.

Build 51709c2af-2021.08.16-01:42
Samsung s7. 
See screenshots attached on screen / profile & log attached.

**Comment by vanelsberg** [comment]
Think this a know issue for AAPS main dev;
Treatments on overview do not refresh in time.

**Comment by robertrub** [comment]
I confirm. I set a 200% profile which has 7U/hr (3.5U/h x 2) but the main screen still shows 3.5U/h
![image](https://user-images.githubusercontent.com/76626474/130127270-b5b9d24a-1032-4dc6-a88b-e43f10b4ce5d.png)
![image](https://user-images.githubusercontent.com/76626474/130127304-b3b44367-4520-4ae5-9f0f-1e27228ebf44.png)

**Comment by vanelsberg** [comment]
Think this is an AAPS main problem (delaying overview updates)
Checking the DASH view should show the correct basal rates.

**Comment by vanelsberg** [comment]
Proposing to close this issue.

Think this bug was solved with dev merge,
https://github.com/0pen-dash/AndroidAPS/pull/132 / dash#9de71e1
