### ISSUE TITLE
Allows for a max basal out of hard limits to be set on dash pod on >100% profile switch

### ISSUE THREAD

**Issue by dexdan** [0pen-dash/AndroidAPS#94]
Local profile was set with a basal rate of 10u/hr. I did a profile switch to 200%. Message quickly appeared to say 'profile set ok', v soon followed by message '<maximal profile basal value> is out of hard limits. 20 limited to 10'.

HOWEVER the pod was not updated with a 10u/hr rate and counting clicks confirmed that 20u/h wax being delivered (66 clicks over 10min). ALSO display indicated 10u/h despite 20u/h being delivered.

I also monitored identical behaviour with 150% profile

Build 51709c2-2021.08.16-01:42
Samsung s7.

Screenshots (inc profile) attached and logs attached from the 200% and 150% examples.

![20210818_185933_BASAL_RATE_PROFILE](https://user-images.githubusercontent.com/8146651/129968134-511a3635-799a-4a85-aaa7-25e0e9de3c10.jpg)
[AndroidAPS_LOG_1629315676773_HARD_LIMITS_200.log](https://github.com/0pen-dash/AndroidAPS/files/7010045/AndroidAPS_LOG_1629315676773_HARD_LIMITS_200.log)
![20210818_203214_HARD_LIMITS_200](https://user-images.githubusercontent.com/8146651/129968357-669e46ab-442b-4af8-ad9a-151040fbfab3.jpg)
![20210818_210303_HARD_LIMITS_150](https://user-images.githubusercontent.com/8146651/129968365-94c6b1c3-91ff-4ddd-8b5e-eab99ebfa654.jpg)
[AndroidAPS_LOG_1629317159091_HARD_LIMITS_150.log](https://github.com/0pen-dash/AndroidAPS/files/7010047/AndroidAPS_LOG_1629317159091_HARD_LIMITS_150.log)

**Comment by vanelsberg** [comment]
Think this is an issue for current AAPS main.

**Comment by dexdan** [comment]
Thanks, have recreated issue in aaps , closing this instance

**Comment by dexdan** [comment]
https://github.com/nightscout/AndroidAPS/issues/657
