### ISSUE TITLE
No countdown of temp basal

### ISSUE THREAD

**Issue by robertrub** [0pen-dash/AndroidAPS#97]
Last connection 3 min ago (a bolus and temp basal). I see last connection : 3 min, last bolus : 3 min but the temp basal counter x min/y min is stuck at 0 min.

![IMG-20210820-WA0007](https://user-images.githubusercontent.com/76626474/130234448-e3e69e60-f1aa-4355-9d60-258b1ad6ab09.jpg)

**Comment by avereha** [comment]
https://github.com/0pen-dash/AndroidAPS/pull/130
