### ISSUE TITLE
Temporary profile changes and targets not ended at the time set

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#98]
**AndroidAPS 2.8.2.2-dev**
**Build**: f9efb49
**Flavor**: fullrelease

**Problem description:**
"Sometimes" (in: not always) Temporary profile changes and targets are not ended at when the time set elapses and
Progress time also does not "count down"

_Expected behavior:_
Temporary profiles and targets should fall back to the default after the time specified.

**Note**: Think this is a main-dev issue - not DASH driver

**Comment by vanelsberg** [comment]
Reated to https://github.com/0pen-dash/AndroidAPS/issues/97?

**Comment by avereha** [comment]
We will need logs and/or steps to reproduce for this issue.

**Comment by vanelsberg** [comment]
Will do. Have not been able to reproduce this since...
